import { NextResponse } from "next/server";
import { generateGeminiNarrative } from "@/lib/gemini";
import { mockAnalysis } from "@/lib/mock-data";

export async function POST(request: Request) {
  const body = (await request.json().catch(() => ({}))) as { location?: string };
  const requestedLocation = body.location ?? "Can Tho, Vietnam";

  try {
    const narrative = await generateGeminiNarrative(mockAnalysis, requestedLocation);

    if (narrative) {
      return NextResponse.json({
        ...mockAnalysis,
        ...narrative,
        requestedLocation,
        source: "gemini",
        notes: [
          "Narrative fields were generated by Gemini from the current demo indicators.",
          "Map-derived percentages and assets are still mocked until geocoding and imagery are wired in."
        ]
      });
    }
  } catch (error) {
    console.error("Gemini narrative generation failed:", error);
  }

  return NextResponse.json({
    ...mockAnalysis,
    requestedLocation,
    source: "mock",
    notes: [
      "Gemini is not configured yet, so the route returned the local mock response.",
      "Add GEMINI_API_KEY to enable Gemini-generated summary, reasons, and recommendations."
    ]
  });
}
